BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: ''
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        id: output_label
        font_size: 48
        color: (1, 1, 0, 1)